### ISSUE TITLE
Any plan for releasing the code of PV-RCNN?

### ISSUE THREAD

**Issue by memoiry** [sshaoshuai/PCDet#1]
Hi, Shaoshuai,

Thanks for your wonderful work! 

I'm wondering if there is a plan for releasing the code of PV-RCNN?

Thanks!

**Comment by sshaoshuai** [comment]
PV-RCNN will be supported in the near future.

**Comment by memoiry** [comment]
@sshaoshuai Is there an approximate time for the release? Thanks for your reply~

**Comment by sshaoshuai** [comment]
maybe one or two months, I will find time to support it.

**Comment by memoiry** [comment]
@sshaoshuai Great! Looking forward to your update.

Best

**Comment by cslxiao** [comment]
Nice work!
The code is not compatible with the latest pytorch (1.4) due to the outdated spconv version.
Any plan to update the dependencies?

**Comment by sshaoshuai** [comment]
Sorry, the codes are tested on pytorch 1.1 and pytorch 1.3, and currently I don't have much time to investigate the dependencies of spconv.

**Comment by willyd** [comment]
The fix to get spconv to work with PyTorch 1.4 is easy. See: https://github.com/traveller59/spconv/pull/105
