### ISSUE TITLE
Simple testing scripts and visualization

### ISSUE THREAD

**Issue by Haotian-Zhang** [sshaoshuai/PCDet#11]
Thank you for your great contributions to this repo. Instead of the test.py scripts to evaluate the performance, could you please also provide some simple testing scripts to do the inference for a single image/ a set of images in the folder, and also provide some scripts/tools for visualization purposes? Looking forward to your reply!

Thank you!

**Comment by sshaoshuai** [comment]
You could refer to https://github.com/kuixu/kitti_object_vis for some visualization codes. Currently I don't have much time to refactor some visualization codes to here (maybe I will do it later when I am free).  
For inference with a set of images, if you means for some kitti scenes, you could write a simple split file to `data/kitti/ImageSets` and create the infos, then inference with this new split file.  You could also write a simpler script for test on specific point clouds without creating infos, I think it should not be complex by modifying the test codes.
