### ISSUE TITLE
AttributeError: int object has no attribute 'shape'

### ISSUE THREAD

**Issue by Gang-Chen-China** [sshaoshuai/PCDet#12]
when is run second , it shows above error at pcdet/models/detectors/detector3d.py/line 303

```
for key, val in model_state_disk.items():
        if key in self.state_dict() and self.state_dict()[key].shape == model_state_disk[key].shape:
        update_model_state[key] = val
        # logger.info('Update weight %s: %s' % (key, str(val.shape)))
```

do you know how to solve it?

**Comment by sshaoshuai** [comment]
Which model does you load? Could you please print out the failed key?

**Comment by sshaoshuai** [comment]
I have uploaded a new version of `1second.pth` to fix this problem, please download the new one.

**Comment by Gang-Chen-China** [comment]
> 
> 
> I have uploaded a new version of `second.pth` to fix this problem, please download the new one.
thanks , i will try later!

**Comment by Gang-Chen-China** [comment]
> 
> 
> I have uploaded a new version of `second.pth` to fix this problem, please download the new one.

thanks , i will try later.
