### ISSUE TITLE
Question about how to sample points in a voxel/pillars

### ISSUE THREAD

**Issue by gujiaqivadin** [sshaoshuai/PCDet#15]
Hello,shishaoshuai!
      Thanks for sharing the excellent code. I have q question about the point sampleing process. In each config model.yaml files, you set `MAX_POINTS_PER_VOXEL = 5 or 32`. But if in a voxel whose points more than 5/32 points or  less than 5/32 points, how do you selcet these points, and where can I change the sampling policy in my own point cloud. Thanks a lot!

**Comment by sshaoshuai** [comment]
Currently the voxelization and sampling are implemented by `spconv` library, which are called in https://github.com/sshaoshuai/PCDet/blob/master/pcdet/datasets/dataset.py#L155 of my codebase.  So you should modify the voxelization codes of `spconv`, or you could also write your own voxelization codes
