### ISSUE TITLE
RuntimeError: result type Byte can't be cast to the desired output type Bool

### ISSUE THREAD

**Issue by asadnorouzi** [sshaoshuai/PCDet#17]
I am getting the following runtime error:

`RuntimeError: result type Byte can't be cast to the desired output type Bool`

It is caused by line 130 in box_coder_utils.py.

**Comment by zwqnju** [comment]
I just change `dir_labels.byte()` to `dir_labels.bool()` and the error is eliminated.

**Comment by asadnorouzi** [comment]
Thank you  @zwqnju. It fixed the error.

**Comment by zwqnju** [comment]
@asadnorouzi I find that using PyTorch 1.1 can also fix this issue, which do not need modifying code. Higher version of PyTorch does not support the code.

**Comment by asadnorouzi** [comment]
@zwqnju Yeah, I figured that this repo has been developed based on Pytorch 1.1. I'm testing it with Pytorch 1.4. It's been OK so far.
