### ISSUE TITLE
Anchor-free RPN head

### ISSUE THREAD

**Issue by s-ryosky** [sshaoshuai/PCDet#19]
I'm interested in trying anchor-free RPN head which is mentioned in [your paper](https://arxiv.org/abs/1907.03670).
Is it supported in this repo?
How should I run?

**Comment by sshaoshuai** [comment]
Currently this repo only contains the implementation of the Part-A2-anchor (which has better performance), and the anchor-free strategy is not supported in this repo at this time.

**Comment by s-ryosky** [comment]
Thank you for your reply.
Do you have a plan to release the code?

**Comment by sshaoshuai** [comment]
It may be released with some point-based methods in the near future.
