### ISSUE TITLE
[###updated for new question] rcnn_loss don't decline when training on my custum dataset

### ISSUE THREAD

**Issue by xzswater** [sshaoshuai/PCDet#24]
As shown on the fig, **### rcnn_loss don't decline** sharply; on the contrary, rpn_loss worked well.
So, what are the possible reasons ? Thank you for your suggestion.

![pcdet-train-roblem](https://user-images.githubusercontent.com/52267702/78104032-fa93ff00-7420-11ea-9f9b-b2994e64bdf9.png)

**Comment by sshaoshuai** [comment]
How about the final mAP?  Sometimes the rcnn loss curve could not well indicate the training process of the network. Also, the rcnn_fg_num seems too low. Maybe you should check the quality of RPN proposals. And also you could modify the RCNN.TARGET_CONFIG.[REG_FG_THRESH, CLS_FG_THRESH, CLS_BG_THRESH] according to your dataset or classes.

**Comment by xzswater** [comment]
@sshaoshuai  Thank you for your valuable advice, i did found some bugs and fixed them !
And i modified the PartA2.yaml configs to fit my custum dataset.
![image](https://user-images.githubusercontent.com/52267702/78768513-96dc7980-79be-11ea-8f0c-3dcfb137ecd1.png)

### But, the recall_rcnn_* and recall_roi_* still very low when i eval on test sub-dataset. Could you help to provide some more suggestions ? Looking forward to your reply .

![image](https://user-images.githubusercontent.com/52267702/78769191-9395bd80-79bf-11ea-8961-25ecf6054e57.png)

In addition, our pointclouds is labeld all 360 degrees, without 2d images. So, i set POINT_CLOUD_RANGE to  [-60, -60, -1.5, 60, 60, 2.5].
Because no 2d images, i'm modifying kitti_object_eval_python/eval.py, so can't provide the mAPs now .

The tensorboard graphs :
![image](https://user-images.githubusercontent.com/52267702/78769416-ee2f1980-79bf-11ea-8ad8-333a04d13eb9.png)
