### ISSUE TITLE
What's the difference between UNet_V0 and UNet_V2?

### ISSUE THREAD

**Issue by YoungZiyu** [sshaoshuai/PCDet#27]
Hi Shaoshuai, I am running your codes about Part-A2, and I find that the pre-trained model uesd UNet_V0 instead of the default UNet_V2 in config files. However, there is only one difference between them in your codes. 

UNet_V0: 
https://github.com/sshaoshuai/PCDet/blob/afd40d822b1330bb010a834673a0aa415c9a1053/pcdet/models/rpn/rpn_unet.py#L188

UNet_V2: 
https://github.com/sshaoshuai/PCDet/blob/afd40d822b1330bb010a834673a0aa415c9a1053/pcdet/models/rpn/rpn_unet.py#L381

Does it really affects the final performance? Thanks for your reply~

**Comment by sshaoshuai** [comment]
The Performance of UNetV0 and UNetV2 should be similar. There is a little mistake on the UNetV0, and I give it just for inference with the Part-A2 pretrained model.
