### ISSUE TITLE
Problem installing pcdet library

### ISSUE THREAD

**Issue by MYSystemLogistics** [sshaoshuai/PCDet#29]
Hi @sshaoshuai,

I'm trying to install pcdet, but when I run `python setup.py develop` I get this error:
```
  File "setup.py", line 26
    print('__version__ = "%s"' % version, file=f)
                                              ^
SyntaxError: invalid syntax
```
How can I solve it?

Thank you for your attention.

**Comment by sshaoshuai** [comment]
Do you use python3 for this repo? If not, please try to use python3.

**Comment by sshaoshuai** [comment]
Have you checked your `spconv` version?  This repo use `spconv v1.0` ([commit 8da6f96](https://github.com/traveller59/spconv/tree/8da6f967fb9a054d8870c3515b1b44eca2103634)) currently.

**Comment by natsume7** [comment]
i get the same problem but  after Run cd ./dist, use pip to install generated whl file ,it work
