### ISSUE TITLE
[###updated for new question] 关于旋转角 变换的困惑，求帮助

### ISSUE THREAD

**Issue by xzswater** [sshaoshuai/PCDet#32]
@sshaoshuai  我们的坐标系跟kitti坐标系不一样（需要做转换），关于代码中旋转角度的细节，有些困惑，烦请赐教~

pcdet/models/rcnn/partA2_rcnn_net.py
![image](https://user-images.githubusercontent.com/52267702/78647274-ebafbf80-78ec-11ea-89b8-c534d9937c28.png)

![image](https://user-images.githubusercontent.com/52267702/78647287-f1a5a080-78ec-11ea-8b9e-77449baf12cb.png)

**Comment by sshaoshuai** [comment]
We have the following definitions: 
1. The LiDAR coordinate denotes the KITTI LiDAR coordinate system, with x: forward, y: left, z: up, and **the direction of zero orientation is along the -y**.
2. The local coordinate denotes the coordinate system of a object, with x: heading direction of this object, y: perpendicular to x, z: up, and **the direction of zero orientation is along the x**. 

Hence, for transforming the LiDAR coordinate to local coordinate,  we should rotate the object points with `ry + np.pi / 2`

**Comment by xzswater** [comment]
@sshaoshuai  Thank you very much !  And, could you help to explan why dir_offset set to pi / 4 ? 

tools/cfgs/PartA2.yaml
![image](https://user-images.githubusercontent.com/52267702/78766049-5f200280-79bb-11ea-98c7-734a230170c3.png)

pcdet/utils/box_coder_utils.py
![image](https://user-images.githubusercontent.com/52267702/78767302-00f41f00-79bd-11ea-8765-93da152f8bbd.png)

**Comment by penghao1990** [comment]
您好，请问为什么需要dir_offset，并且设置为pi/4呢？我不明白，能否帮助一下。谢谢！

**Comment by DeclK** [comment]
I found someone else's [answer](https://github.com/open-mmlab/OpenPCDet/issues/80#issuecomment-641865296) might solve this question
