### ISSUE TITLE
Dockerfile lost some lib

### ISSUE THREAD

**Issue by chaomath** [sshaoshuai/PCDet#34]
These libs are not installed in the dockerfile:
 'numba',
 'tensorboardX',
'easydict',
'pyyaml'

**Comment by trn84** [comment]
Line 93:  shapely fire pybind11 easydict tensorboardX pyyaml protobuf scikit-image tqdm pillow flask flask_cors

**Comment by tojimahammatov** [comment]
Some of them will be installed when you run:`python(3) setup.py develop`. 

Look through `setup.py` file.
