### ISSUE TITLE
Some problems about function "boxes3d_to_bevboxes_lidar_torch" in the file "box_utils.py"

### ISSUE THREAD

**Issue by GangZhang842** [sshaoshuai/PCDet#35]
I really understand that the function "boxes3d_to_bevboxes_lidar_torch" aims to convert a 3D box [x, y, z, w, l, h, ry] into the bev form [x1, y1, x2, y2, ry] when conducting NMS. However, there may be some mistakes in the function code. "boxes_bev[:, 0], boxes_bev[:, 1] = cu - half_w, cv - half_l" does not consider yaw angle. I mean "boxes_bev[:, 0]" is not the real x1

**Comment by sshaoshuai** [comment]
Here x1/y1/x2/y2 are just the canonical coordinate, and the `ry` is used to calculate the real x1/y1/x2/y2 when we need them to calculate the rotated IoU.

**Comment by GangZhang842** [comment]
Okay~ I see! Thank you!
