### ISSUE TITLE
About 3D Object Detection Prediction's Rotation Result Problem

### ISSUE THREAD

**Issue by ltphy** [sshaoshuai/PCDet#48]
To train your model, I use the lidar coordinate system with input of each bounding box as 
`[x, y, z, w, l, h, Rz]` with pointpillar configuration. The anchor generator of each object in the config is `[0, 3.14]` 
However, the prediction result of Rz is around ` 6.` which is outside the range of ` [-pi, pi]`.
Do you have any idea about this problem?
Thank you for your excellent work.

**Comment by sshaoshuai** [comment]
Actually it doesn't matter since the angle is a periodic function, and you could convert Rz to [-pi, pi] by Rz = Rz % (2pi) - pi if you like.
