### ISSUE TITLE
Question about the  training strategy

### ISSUE THREAD

**Issue by jingyi-zhang** [sshaoshuai/PCDet#5]
Thanks for your wonderful work~
But I am puzzled on the training strategy, are the two stages of Part A^2 Net  trained separately like PointRCNN? 
I have never submitted results on kitti website, but I am trying to do a research job based on this dataset currently, so I wonder is it possible to train easy cases and hard cases  respectively?

**Comment by sshaoshuai** [comment]
In this repo, the two-stage networks, like PartA2, are trained jointly, so you just need to run once for each model. 
It's possible to train easy and hard cases separately, but I think it may confuse the network since the objects of difficulty levels  have no clear split lines.

**Comment by jingyi-zhang** [comment]
Thanks, I got it, you are too good!
