### ISSUE TITLE
General questions regarding lidar data

### ISSUE THREAD

**Issue by nicholasguimaraes** [sshaoshuai/PCDet#53]
Hello, I have a couple of doubts regarding how I can train the model on my own data.

1 - Do I need to use specifically one of the Velodyne lidar sensors to gather data?

2 - Does it automatically produces a calibration.txt file of every frame when saved? Essentially what is calibration for? 

3 - How can I label my point cloud data? 
Would this software work?
https://scale.com/3d-sensor-fusion

It would be great if you could help me clarifying these questions.

Thank you.

**Comment by zjx99** [comment]
@nicholasguimaraes 
Hello,
Have you solved the third problem?  Did you use that software you mentioned?  Thanks!
