### ISSUE TITLE
I had a read plane file error...

### ISSUE THREAD

**Issue by Ahnsungmoon** [sshaoshuai/PCDet#57]
Could you share the planes files?

**Comment by sshaoshuai** [comment]
You could download the plane from https://drive.google.com/file/d/1d5mq0RXRnvHPVeKx6Q612z0YRO1t2wAp/view, which is already mentioned in the README.

**Comment by Ahnsungmoon** [comment]
Thank you!!


2020년 5월 11일 (월) 오후 6:06, Shaoshuai Shi <notifications@github.com>님이 작성:
