### ISSUE TITLE
What does the road planes for data augmentation do?

### ISSUE THREAD

**Issue by Hastyrush** [sshaoshuai/PCDet#58]
Hello, you mentioned that road planes can be downloaded additionally for data augmentation of the KITTI 3D Object detection dataset during training. May I know what does the augmentation actually mean or do? Does it remove the road plane or transforms it in a certain way? And how does it help with the training of the model.

Thanks a lot!
<img width="698" alt="Capture" src="https://user-images.githubusercontent.com/19281594/81390629-5f442700-914e-11ea-8ae0-45af97b09ba8.PNG">

**Comment by sshaoshuai** [comment]
The road planes are used for GT sampling augmentation, where we could 'paste' the additional GTs to the road plane of current scene.

**Comment by Hastyrush** [comment]
I see. Thanks a lot for the information! Will be closing this issue.

**Comment by Petros626** [comment]
@sshaoshuai can you show me in the code where the gt_database .bin files are loaded to be gt_sampled during training? And where the safety checks are made, that there is no overlapping with other objects.

Thank you very much!
