### ISSUE TITLE
 How to perform test without Label_2 folder, like in KITTI testing?

### ISSUE THREAD

**Issue by KevinDu1** [sshaoshuai/PCDet#7]

**Comment by sshaoshuai** [comment]
You could directly inference on test set by setting `MODEL.TEST.SPLIT=test`.  Add config `--save_to_file` to save the predicted results to files.

**Comment by KevinDu1** [comment]
@sshaoshuai Thank U for your help! Another question, How to add 3D labels to my dataset?

**Comment by sshaoshuai** [comment]
What does you mean for adding 3D labels for your dataset?
