### ISSUE TITLE
kitti calibration bug?

### ISSUE THREAD

**Issue by bigsheep2018** [sshaoshuai/PCDet#77]
Hello PCDet team @codyreading @sshaoshuai,

Thanks for sharing this framework.

I found some interesting labels in forms of 3d bbox based on your code.
Basically, I just visualize the 'gt_box_lidar' of the kitti_infos_xxx.pkl files and found the 3d box is not closely fitting the vehicle points' surface. Some box even cannot cover the points belong to it. 

Examples in training split are shown as follows 
000014: the box is kind of too large for the car
![image](https://user-images.githubusercontent.com/45345643/83091745-7bdcda80-a0ce-11ea-9416-d412a44d6e5f.png)

000082: the boxes seems cannot cover the points belong to them
![image](https://user-images.githubusercontent.com/45345643/83092679-5e107500-a0d0-11ea-9232-775eb0adc5e9.png)

I can find more similar examples in the generated labels.
Do I miss something in PCDet or indeed there are some errors of the labels?

**Comment by codyreading** [comment]
Hi @bigsheep2018,

Looks like these are just non-perfect labels. 

In 000014, it's hard to tell if the box is too lagre for the car, as only the LiDAR points belonging the the front of the car are visible

In 000082, the points are only slightly in front of the boxes.

I visualized these samples myself, and found the same thing.

**Comment by bigsheep2018** [comment]
@codyreading 
Thanks for the reply.

**Comment by LZDSJTU** [comment]
> @codyreading
> Thanks for the reply.

Hi, I want to ask which tool you use to visualize the detection result. Thank you.

**Comment by codyreading** [comment]
Hello,

I use [this](https://github.com/kujason/scene_vis) tool which uses VTK to visualize 3D scenes
