### ISSUE TITLE
local variable 'img_shape' referenced before assignment

### ISSUE THREAD

**Issue by cslxiao** [sshaoshuai/PCDet#8]
When cfg.DATA_CONFIG.FOV_POINTS_ONLY is false, local variable 'img_shape' will be referenced before assignment in line 437 of kitti_dataset.py.

**Comment by sshaoshuai** [comment]
Thanks! It has been fixed in [commit 826faec](https://github.com/sshaoshuai/PCDet/commit/826faeca79869198dde44a874156197d370e93d9). By the way, please do not set FOV_POINTS_ONLY=False since the codes don't support this feature currently.
