### ISSUE TITLE
something wrong when running train.py

### ISSUE THREAD

**Issue by Cjmmmmmm** [sshaoshuai/PCDet#9]
File "/home/PCDet/pcdet/datasets/kitti/kitti_dataset.py", line 398, in __getitem__
    sample_idx = info['point_cloud']['lidar_idx']
KeyError: 'lidar_idx'

**Comment by PolyU-IPNL** [comment]
I have encounter the same problem, how would you solve it?

**Comment by wind19970924** [comment]
I have encounter the same problem, how would you solve it?

**Comment by Rajat-Mehta** [comment]
@Cjmmmmmm @wind19970924 @PolyU-IPNL did any one of you solve this issue? If yes, how? I am also getting this error when training the pvrcnn model on kitti dataset.

**Comment by twangnh** [comment]
same problem

**Comment by Dinghow** [comment]
same problem

**Comment by dailingjun** [comment]
The pkl files may be generated by mmdetection3d in which the keys are different. 
Delete or move all the pkl files. Re-generate the data infos by running the following command:
python -m pcdet.datasets.kitti.kitti_dataset create_kitti_infos tools/cfgs/dataset_configs/kitti_dataset.yaml
